import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import path from "node:path";
import type { DocumentRecord, LoadedProjectConfig } from "../types/memoryTypes.js";

export interface SourceEvidence {
  sourcePaths: string[];
  sourceHash: string;
}

export interface MarkdownSummary {
  title: string;
  status: "ok" | "missing_evidence";
  bullets: string[];
}

const PLACEHOLDER_PATTERNS = [
  /待填写/,
  /待确认/,
  /TODO/i,
  /missing evidence/i,
  /当前文件只是模板/,
  /不应自动推断/,
  /不要凭记忆/
];

const TEMPLATE_DOCUMENT_PATTERNS = [
  /当前文件只是模板/,
  /当前文件只提供模板/,
  /文档模板/,
  /待填写内容/,
  /规则模板/,
  /模块记录模板/,
  /模式文档模板/
];

export function toProjectPath(projectRoot: string, filePath: string): string {
  return path.relative(projectRoot, filePath).replace(/\\/g, "/");
}

export function absoluteProjectPath(loaded: LoadedProjectConfig, projectPath: string): string {
  return path.resolve(loaded.projectRoot, projectPath);
}

export async function fileHash(filePath: string): Promise<string> {
  return createHash("sha256").update(await readFile(filePath)).digest("hex");
}

export async function sourceEvidence(projectRoot: string, filePaths: string[]): Promise<SourceEvidence> {
  const existing = filePaths.filter((filePath) => existsSync(filePath)).sort();
  const hasher = createHash("sha256");
  const sourcePaths: string[] = [];
  for (const filePath of existing) {
    const projectPath = toProjectPath(projectRoot, filePath);
    sourcePaths.push(projectPath);
    hasher.update(projectPath);
    hasher.update(await readFile(filePath));
  }
  return {
    sourcePaths,
    sourceHash: hasher.digest("hex")
  };
}

export async function readIndexedDocuments(loaded: LoadedProjectConfig): Promise<DocumentRecord[]> {
  const documentsPath = path.join(loaded.resolvedMemoryOutputRoot, "index", "documents.jsonl");
  try {
    const text = await readFile(documentsPath, "utf8");
    return text
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter(Boolean)
      .map((line) => JSON.parse(line) as DocumentRecord);
  } catch {
    return [];
  }
}

export function extractTitle(text: string, fallback: string): string {
  const heading = text.split(/\r?\n/).find((line) => /^#\s+/.test(line));
  return heading?.replace(/^#\s+/, "").trim() || fallback;
}

function isPlaceholderLine(line: string): boolean {
  return PLACEHOLDER_PATTERNS.some((pattern) => pattern.test(line));
}

export function extractEvidenceBullets(text: string, limit = 8): string[] {
  const bullets: string[] = [];
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#") || line === "```markdown" || line === "```") continue;
    if (isPlaceholderLine(line)) continue;
    if (/^[-*]\s+/.test(line)) {
      const value = line.replace(/^[-*]\s+/, "").trim();
      if (value && !isPlaceholderLine(value)) bullets.push(value);
    } else if (/^[^:：]{2,40}[:：]\s*\S+/.test(line)) {
      bullets.push(line);
    }
    if (bullets.length >= limit) break;
  }
  return bullets;
}

export function summarizeMarkdown(text: string, fallbackTitle: string): MarkdownSummary {
  const title = extractTitle(text, fallbackTitle);
  const isTemplateDocument = TEMPLATE_DOCUMENT_PATTERNS.some((pattern) => pattern.test(text));
  if (isTemplateDocument) {
    return {
      title,
      status: "missing_evidence",
      bullets: ["TODO / missing evidence"]
    };
  }
  const bullets = extractEvidenceBullets(text);
  if (bullets.length === 0) {
    return {
      title,
      status: "missing_evidence",
      bullets: ["TODO / missing evidence"]
    };
  }
  return {
    title,
    status: "ok",
    bullets
  };
}

export async function summarizeDocument(filePath: string, fallbackTitle = path.basename(filePath)): Promise<MarkdownSummary> {
  const text = await readFile(filePath, "utf8");
  return summarizeMarkdown(text, fallbackTitle);
}

export function generatedMarkdownHeader(evidence: SourceEvidence, generatedAt = new Date().toISOString()): string {
  return [
    "<!-- Generated by Project Memory System. Do not edit manually. -->",
    `sourcePaths: ${evidence.sourcePaths.length > 0 ? evidence.sourcePaths.join(", ") : "TODO / missing evidence"}`,
    `sourceHash: ${evidence.sourceHash}`,
    `generatedAt: ${generatedAt}`,
    ""
  ].join("\n");
}
